name: unit-tests

on:
  pull_request:
    branches:
      - master
jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run tests
        run: make unit-test
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60